### ISSUE TITLE
How to make extension of the new type 

### ISSUE THREAD

**Issue by MattWangming** [cosmos/amino-js#2]
Hi there, 
   It`s really a fantastic project here for cosmos-sdk as js output! Let me introduce myself, I'm from QOS Group, a partner in cosmos ecosystem. It`s quite new and suitable for us when there is blockchain `QOS` based on tendermint rather than cosmos itself. 
   I want to extend the specific type of `qos tx` as the same way of other cosmos types deployed.
  Is there more detailed instruction than `extend.md`? 
  Thanks~

PS: you can also refer to our issue if you are interested:   https://github.com/QOSGroup/qweb/issues/22

**Comment by jordansexton** [comment]
I just saw this issue, but it seems like the original tracking issue @ https://github.com/QOSGroup/qweb/issues/22 was closed shortly after this issue was created, so I'll close this for now.

If you do decide to use this library, in addition to [`EXTEND.md`](https://github.com/cosmos/amino-js/blob/extend/EXTEND.md) (which has some links to Go code for extending the library) the there are a few forks of the library that might illustrate how to add types and build it, such as this: https://github.com/hschoenburg/amino-js/commits/master
